export const SCREENSHOT_CONTEXT_MENU_ID = 'rabby-screenshot-context-menu';

export const SCREENSHOT_CONTEXT_MENU_CLICKED =
  'RABBY_SCREENSHOT_CONTEXT_MENU_CLICKED';

export const SCREENSHOT_FEEDBACK_ENTRY_CLICKED =
  'RABBY_SCREENSHOT_FEEDBACK_ENTRY_CLICKED';
