export const ALARMS_SYNC_CHAINS = 'ALARMS_SYNC_CHAINS';
export const ALARMS_SYNC_METAMASK_DAPPS = 'ALARMS_SYNC_METAMASK_DAPPS';
export const ALARMS_SYNC_CURRENCY_LIST = 'ALARMS_SYNC_CURRENCY_LIST';
export const ALARMS_USER_ENABLE = 'ALARMS_USER_ENABLE';
export const ALARMS_SYNC_DEFAULT_RPC = 'ALARMS_SYNC_DEFAULT_RPC';
