export const ALARMS_AUTO_LOCK = 'ALARMS_AUTO_LOCK';
export const ALARMS_RPC_CACHE = 'ALARMS_RPC_CACHE';
export const ALARMS_RELOAD_TX = 'ALARMS_RELOAD_TX';
export const ALARMS_SYNC_CHAINS = 'ALARMS_SYNC_CHAINS';
export const ALARMS_REFRESH_BALANCE = 'ALARMS_REFRESH_BALANCE';
