const ROW_SIZES = {
  ROW_INNER_HEIGHT: /* 60 */ 54,
  ROW_GAP: 8,
  RISKY_ROW_INNER_HEIGHT: /* 96 */ 90,
};

export const ROW_HEIGHT = ROW_SIZES.ROW_INNER_HEIGHT + ROW_SIZES.ROW_GAP;
export const RISKY_ROW_HEIGHT =
  ROW_SIZES.RISKY_ROW_INNER_HEIGHT + ROW_SIZES.ROW_GAP;

export const SCROLLBAR_WIDTH = 4;
