const ROW_SIZES = {
  ROW_INNER_HEIGHT: 60,
  ROW_GAP: 12,
  RISKY_ROW_INNER_HEIGHT: 96,
};
const ROW_GAP = 12;

export const ROW_HEIGHT = ROW_SIZES.ROW_INNER_HEIGHT + ROW_GAP * 2;
export const RISKY_ROW_HEIGHT = ROW_SIZES.RISKY_ROW_INNER_HEIGHT + ROW_GAP * 2;

export const SCROLLBAR_WIDTH = 6;
