# Each PR will build preview site that help to check code is work as expect.

name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    tags:
      - '*'

jobs:
  build-pro:
    name: build pro
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.1'
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Enable Corepack
        run: corepack enable

      - name: Use NPM Token with organization read access
        uses: heisenberg-2077/use-npm-token-action@v1
        with:
          token: '${{ secrets.NPM_AUTH_TOKEN }}'

      - name: Install dependencies
        run: yarn install --immutable

      - name: build
        run: yarn build:pro

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          name: Rabby_${{github.sha}}
          path: dist
          retention-days: 7

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'push' }}
        with:
          name: Rabby_${{github.ref_name}}
          path: dist
          retention-days: 7

  build-debug:
    name: build debug
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.1'
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Enable Corepack
        run: corepack enable

      - name: Use NPM Token with organization read access
        uses: heisenberg-2077/use-npm-token-action@v1
        with:
          token: '${{ secrets.NPM_AUTH_TOKEN }}'

      - name: Install dependencies
        run: yarn install --immutable

      - name: build
        run: yarn build:debug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          name: Rabby_${{github.sha}}_debug
          path: dist
          retention-days: 7

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'push' }}
        with:
          name: Rabby_${{github.ref_name}}_debug
          path: dist
          retention-days: 7
