# Each PR will build preview site that help to check code is work as expect.

name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    tags:
      - '*'

jobs:
  build-pro:
    name: build pro
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22.17.1'
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Enable Corepack
        run: corepack enable

      - name: Use NPM Token with organization read access
        uses: heisenberg-2077/use-npm-token-action@99c5b17c84a15e44fdcef6712b34b76f8f0493b0 # v1
        with:
          token: '${{ secrets.NPM_AUTH_TOKEN }}'

      - name: Install dependencies
        run: yarn install --immutable

      - name: build
        run: yarn build:pro

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          name: Rabby_${{github.sha}}
          path: dist
          retention-days: 7

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: ${{ github.event_name == 'push' }}
        with:
          name: Rabby_${{github.ref_name}}
          path: dist
          retention-days: 7

  build-debug:
    name: build debug
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22.17.1'
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Enable Corepack
        run: corepack enable

      - name: Use NPM Token with organization read access
        uses: heisenberg-2077/use-npm-token-action@99c5b17c84a15e44fdcef6712b34b76f8f0493b0 # v1
        with:
          token: '${{ secrets.NPM_AUTH_TOKEN }}'

      - name: Install dependencies
        run: yarn install --immutable

      - name: build
        run: yarn build:debug

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          name: Rabby_${{github.sha}}_debug
          path: dist
          retention-days: 7

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: ${{ github.event_name == 'push' }}
        with:
          name: Rabby_${{github.ref_name}}_debug
          path: dist
          retention-days: 7
