name: PR Scan

on:
  pull_request:
    branches:
      - develop

jobs:
  prscan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22'

      - name: Run prscan
        env:
          INPUT_PRSCAN_BOT_TOKEN: ${{ secrets.PRSCAN_BOT_TOKEN }}
        run: npx prscan github ${{ github.event.pull_request.html_url }} --reply
